"""Add name column to supplier_application

Revision ID: 696eed5ce7e6
Revises: a778f946d189
Create Date: 2025-07-27 15:23:25.313800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696eed5ce7e6'
down_revision = 'a778f946d189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_supplier_application_product_id', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
