"""Add name column to supplier_application

Revision ID: a14270fc675b
Revises: 696eed5ce7e6
Create Date: 2025-07-27 15:39:18.682006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14270fc675b'
down_revision = '696eed5ce7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False))
        batch_op.drop_column('messaage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messaage', sa.TEXT(), nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
