"""Add name column to supplier_application

Revision ID: a778f946d189
Revises: bc2d0a35aece
Create Date: 2025-07-27 15:18:30.525920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a778f946d189'
down_revision = 'bc2d0a35aece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cartitem_cart_id', 'cart', ['cart_id'], ['id'])

    with op.batch_alter_table('supplier_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('products', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('message')
        batch_op.drop_column('products')
        batch_op.drop_column('website')
        batch_op.drop_column('name')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
